# Generated by Django 2.2.13 on 2020-07-18 06:13

from django.db import migrations, models
import django.db.models.deletion
import mood.models.mood


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('openid', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='WX唯一ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('fakename', models.CharField(max_length=32, verbose_name='用户匿名')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=mood.models.mood.user_directory_path, verbose_name='附图')),
                ('click_counter', models.IntegerField(default=0, verbose_name='点击数')),
                ('comment_counter', models.IntegerField(default=0, verbose_name='评论数')),
                ('like_counter', models.IntegerField(default=0, verbose_name='点赞数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood', to='mood.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '心情',
                'verbose_name_plural': '心情',
                'ordering': ('create_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否软删除')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('click_counter', models.IntegerField(default=0, verbose_name='点击数')),
                ('like_counter', models.IntegerField(default=0, verbose_name='点赞数')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mood.Mood', verbose_name='心情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mood.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '心情',
                'ordering': ('create_at',),
            },
        ),
    ]
