# Generated by Django 2.2.13 on 2021-05-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-create_at',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='mood',
            options={'ordering': ('-create_at',), 'verbose_name': '心情', 'verbose_name_plural': '心情'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-create_at',), 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
