# Generated by Django 2.2.13 on 2021-05-29 19:01

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_auto_20210530_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default=common.utils.gen_id_by_uuid, max_length=80, primary_key=True, serialize=False, verbose_name='WX唯一ID'),
        ),
    ]
